compile:
	mvn compile
run:
	mvn compile exec:java -Dexec.mainClass="com.mycom.app.helloworld.HelloWorld" -Dexec.arguments='Hello World Bye Bye yeah' 
runPGP:
	mvn compile exec:java -Dexec.mainClass="com.mycom.app.helloworld.PGPProcessor" -Dexec.arguments='Hello World Bye Bye yeah' 
runSig:
	mvn compile exec:java -Dexec.mainClass="com.mycom.app.helloworld.TransbizSignature" -Dexec.arguments='Hello World Bye Bye yeah' 
